<?php

$attributes = array(
'cn' => "Common Name",
'sn' => "Surname",
'audio' => "",
'carLicence' =>"",
'businessCategory' => "",
'departmentNumber' => "",
'displayName' => "",
'employeeNumber' => "",
'employeeType' => "",
'givenName' => "",
'homePhone' => "",
'initials' => "",
'jpegPhoto' => "",
'labeledURI' => "",
'mail' => "",
'manager' => "",
'mobile' => "",
'o' => "",
'pager' => "",
'photo' => "",
'preferredLanguage' => "",
'roomNumber' => "",
'secretary' => "",
'uid' => "",
'userCertificate' => "",
'userPKCS12' => "",
'userSMIMECertificate' => "",
'x500UniqueIentifier' => "",
'destinationIndicator' => "",
'fax' => "",
'indernationiSDNNumber' => "",
'l' => "",
'ou' => "",
'physicalDeliveryOfficeNae' => "",
'postalAddress' => "",
'postOfficeBox' => "",
'preferredDeliveryMethod' => "",
'registeredAddress' => "",
'st' => "",
'street' => "",
'telephoneNumber' => "",
'teletexTerminalIdentifier' => "",
'telexNumber' => "",
'title' => "",
'x121Address' => "",
'description' => "",
'seeAlso' => "",
'telephoneNumber' => "",
'userPassword' => "",
'dn'=>"",



);