<?php

$attributes = array(
'cn' => "Common Name",
'sn' => "Surname",
'audio' => "",
'carLicence' =>"",
'businessCategory' => "",
'departmentNumber' => "",
'displayName' => "Display Name",
'employeeNumber' => "",
'employeeType' => "",
'givenName' => "Given Name",
'homePhone' => "Home Phone",
'initials' => "Initials",
'jpegPhoto' => "",
'labeledURI' => "",
'mail' => "Email Address",
'manager' => "Manager",
'mobile' => "Mobile Number",
'o' => "Organisation",
'pager' => "",
'photo' => "",
'preferredLanguage' => "Preferred Language",
'roomNumber' => "",
'secretary' => "",
'uid' => "Username",
'userCertificate' => "",
'userPKCS12' => "",
'userSMIMECertificate' => "",
'x500UniqueIentifier' => "",
'destinationIndicator' => "",
'fax' => "",
'indernationiSDNNumber' => "",
'l' => "",
'ou' => "",
'physicalDeliveryOfficeNae' => "",
'postalAddress' => "",
'postOfficeBox' => "",
'preferredDeliveryMethod' => "",
'registeredAddress' => "",
'st' => "Street",
'street' => "",
'telephoneNumber' => "",
'teletexTerminalIdentifier' => "",
'telexNumber' => "",
'title' => "",
'x121Address' => "",
'description' => "",
'seeAlso' => "",
'telephoneNumber' => "",
'userPassword' => "",
'dn'=>"Distinguished Name",



);