<?php

$attributes = array(
'cn' => "Common Name",
'sn' => "Surname",
'audio' => "",
'carlicence' =>"",
'businesscategory' => "",
'departmentnumber' => "",
'displayname' => "Display Name",
'employeenumber' => "",
'employeetype' => "",
'givenname' => "Given Name",
'homephone' => "Home Phone",
'initials' => "Initials",
'jpegphoto' => "",
'mail' => "Email Address",
'manager' => "Manager",
'mobile' => "Mobile Number",
'o' => "Organisation",
'pager' => "",
'photo' => "",
'preferredlanguage' => "Preferred Language",
'roomnumber' => "",
'secretary' => "",
'uid' => "Username",
'usercertificate' => "",
'userpkcs12' => "",
'usersmimecertificate' => "",
'x500uniqueidentifier' => "",
'destinationindicator' => "",
'fax' => "",
'indernationisdnnumber' => "",
'l' => "",
'ou' => "",
'physicaldeliveryofficenae' => "",
'postaladdress' => "",
'postofficebox' => "",
'preferreddeliverymethod' => "",
'registeredaddress' => "",
'st' => "",
'street' => "",
'telephonenumber' => "",
'teletexterminalidentifier' => "",
'telexnumber' => "",
'title' => "",
'x121address' => "",
'description' => "",
'seealso' => "",
'telephoneNumber' => "",
'userpassword' => "Password",
'dn'=>"Distinguished Name",
'gidnumber'=>"Group ID",
'homedirectory'=>"Home Directory",
'uidnumber'=>"User ID",
'loginshell'=>"Login Shell",
'labeleduri'=>"Homepage",

);

$hiddenAttrs = array(
'userpassword',
'objectclass',
);